### ISSUE TITLE
Too few arguments to function `Feeds::_get_title()`

### ISSUE THREAD

**Issue by wrobelda** [resticDOG/tt-rss-plgin-ntfy#9]
Hi there,

With a current version of TT-RSS, this plugin fails with:

```
[15:31:49/13] Received SIGCHLD, 1 active tasks left.
{"status":1,"request":"81190096-9943-4b08-98bb-14104138ac7b"}PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Feeds::_get_title(), 1 passed in /var/www/html/tt-rss/plugins.local/ntfy/init.php on line 215 and at least 2 expected in /var/www/html/tt-rss/classes/Feeds.php:1145
Stack trace:
#0 /var/www/html/tt-rss/plugins.local/ntfy/init.php(215): Feeds::_get_title()
#1 /var/www/html/tt-rss/plugins.local/ntfy/init.php(199): Ntfy->send_notification()
#2 /var/www/html/tt-rss/classes/RSSUtils.php(936): Ntfy->hook_article_filter_action()
#3 /var/www/html/tt-rss/update.php(226): RSSUtils::update_rss_feed()
#4 {main}
  thrown in /var/www/html/tt-rss/classes/Feeds.php on line 1145
[15:31:50/287] !! Fatal error: Uncaught ArgumentCountError: Too few arguments to function Feeds::_get_title(), 1 passed in /var/www/html/tt-rss/plugins.local/ntfy/init.php on line 215 and at least 2 expected in /var/www/html/tt-rss/classes/Feeds.php:1145
Stack trace:
#0 /var/www/html/tt-rss/plugins.local/ntfy/init.php(215): Feeds::_get_title()
#1 /var/www/html/tt-rss/plugins.local/ntfy/init.php(199): Ntfy->send_notification()
#2 /var/www/html/tt-rss/classes/RSSUtils.php(936): Ntfy->hook_article_filter_action()
#3 /var/www/html/tt-rss/update.php(226): RSSUtils::update_rss_feed()
#4 {main}
  thrown (classes/Feeds.php:1145)
[15:31:50/287]
[15:31:50/284] <= 1.2150 (sec) exit code: 1
[15:31:50/284] !! Last error: Update process failed with exit code: 1 ()
```

**Comment by resticDOG** [comment]
Fixed in the latest commit. It should now work correctly with v26.01-2427fe3e. Thanks!
